---
version: 2
plan:
  project-key: PROJ
  key: PLAN
  name: plan1
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
# Checkout Task will be added implicitly during Specs import
  - any-task:
      plugin-key: aqua-scanner.aqua-scanner:aqua-scanner
      configuration:
        globalApiUrl: http://18.117.86.8:8080/
        globalAquaPassword: '@Password1'
        registry: Docker Hub
        imageName: ubuntu:latest
        globalScannerImage: registry.aquasec.com/scanner:5.3
        locationType: hosted
        aquaConfig: current
        globalAquaUser: administrator
        useContextVariable: 'false'
        checkonly: 'true'
        showNegligible: 'true'
        globalCaCertificates: 'true'
        register: 'true'
triggers: []
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: PROJ-PLAN
plan-permissions:
- roles:
  - logged-in
  - anonymous
  permissions:
  - view
- users:
  - bamboo
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
...
