---
version: 2
plan:
  project-key: PROJ
  key: SPEC
  name: SPEC
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: 'false'
  - script:
      interpreter: SHELL
      scripts:
      - docker build . --no-cache -t bamboo-agent -f Dockerfile
  - any-task:
      plugin-key: aqua-scanner.aqua-scanner:aqua-scanner
      configuration:
        globalApiUrl: http://18.117.86.8:8080/
        globalAquaPassword: '@Password1'
        registry: Docker Hub
        imageName: centos:latest
        globalScannerImage: registry.aquasec.com/scanner:5.3
        locationType: hosted
        aquaConfig: current
        globalAquaUser: administrator
        useContextVariable: 'false'
        checkonly: 'true'
        showNegligible: 'true'
        globalCaCertificates: 'true'
        register: 'true'
triggers:
- polling:
    period: '180'
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: PROJ-SPEC
plan-permissions:
- users:
  - bamboo
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
...
